version: "3.8"
services:
  dashboard-api:
    image: ghcr.io/stichting-crow/dashboarddeelmobiliteit-api:1.26.1
    depends_on:
        - redis
        - postgresql
    environment:
      DB_NAME: dashboarddeelmobiliteit
      DB_HOST: postgresql
      DB_USER: postgres
      DB_PASSWORD: ${PGPASSWORD}
      BASE_URL_FUSIONAUTH: http://fusionauth:9001
      FUSIONAUTH_APIKEY: ${FUSIONAUTH_API_KEY}
      APP_ID: ${FUSIONAUTH_APP_ID}
      TIMESCALEDB_NAME: dashboarddeelmobiliteit
      TIMESCALE_DB_HOST: postgresql
      TIMESCALE_DB_PASSWORD: ${PGPASSWORD}
      TIMESCALE_DB_USER: postgres
      TIMESCALEDB_PORT: "5432"
      REDIS_URL: redis
    restart: always
    
    ports:
      - 127.0.0.1:8002:8000

    networks:
      - backend

  admin-api:
    image: ghcr.io/stichting-crow/dashboarddeelmobiliteit-admin-api:1.2.1
    depends_on:
        - redis
        - postgresql
    environment:
      DB_NAME: dashboarddeelmobiliteit
      DB_HOST: postgresql
      DB_USER: postgres
      DB_PASSWORD: ${PGPASSWORD}
      BASE_URL_FUSIONAUTH: http://fusionauth:9001
      FUSIONAUTH_APIKEY: ${FUSIONAUTH_API_KEY}
      APP_ID: ${FUSIONAUTH_APP_ID}
      BASE_URL_KONG_ADMIN: http://kong:8001
    restart: always

    networks:
      - backend

  od-api:
    image: ghcr.io/stichting-crow/dashboarddeelmobiliteit-od-api:1.0
    depends_on:
        - redis
        - postgresql
    environment:
      DB_NAME: dashboarddeelmobiliteit
      DB_HOST: postgresql
      DB_USER: postgres
      DB_PASSWORD: ${PGPASSWORD}
      TZ: Europe/Amsterdam
    restart: always

    networks:
      - backend

  policy-api:
    image: ghcr.io/stichting-crow/dd-policy-api:1.3.3
    depends_on:
        - redis
        - postgresql
    environment:
      DB_NAME: dashboarddeelmobiliteit
      DB_HOST: postgresql
      DB_USER: postgres
      DB_PASSWORD: ${PGPASSWORD}
      REDIS_URL: redis
    restart: always

    networks:
      - backend

networks:
  backend:
    name: backend
    external: true