version: "3.8"
services:
  data-importer:
    image: ghcr.io/stichting-crow/dd-data-importer:1.9.1
    depends_on:
        - redis
        - postgresql
        - tile38
    environment:
      DEV: false
      DB_NAME: dashboarddeelmobiliteit
      DB_USER: postgres
      DB_HOST: postgresql
      DB_PASSWORD: ${PGPASSWORD}
      DB_PORT: 5432
      REDIS_HOST: redis:6379
      TILE38_HOST: tile38:9851

    networks:
      - backend
    restart: always

  zone-stats-aggregator:
    image: ghcr.io/stichting-crow/dd-zone-stats-aggregator:1.0.2
    depends_on:
        - redis
        - tile38
        - postgresql
    environment:
      DB_NAME: dashboarddeelmobiliteit
      DB_HOST: postgresql
      DB_USER: postgres
      DB_PASSWORD: ${PGPASSWORD}
      TIMESCALE_DB_NAME: dashboarddeelmobiliteit
      TIMESCALE_DB_HOST: postgresql
      TIMESCALE_DB_PASSWORD: ${PGPASSWORD}
      TIMESCALE_DB_USER: postgres
      TIMESCALEDB_PORT: "5432"
      REDIS_URL: redis
      TILE38_URL: tile38
    restart: always
    
    networks:
      - backend

  microhubs-controller:
    image: ghcr.io/stichting-crow/dd-microhubs-controller:1.5.3
    depends_on:
        - redis
        - tile38
        - postgresql
    environment:
      DB_NAME: dashboarddeelmobiliteit
      DB_HOST: postgresql
      DB_USER: postgres
      DB_PASSWORD: ${PGPASSWORD}
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN} 
      REDIS_URL: redis
      TILE38_URL: tile38
    restart: always
  
    networks:
        - backend

networks:
  backend:
    name: backend
    external: true