version: "3.8"
services:

  postgresql:
    image: timescale/timescaledb-ha:pg15
    command: postgres -c 'max_connections=200' 
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres:/home/postgres/pgdata/data
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
    restart: always
    
  redis:
    image: redis:7.2-alpine
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis:/var/lib/redis
    networks:
      - backend
    restart: always

  tile38:
    image: tile38/tile38:1.32.0
    command: tile38-server --appendonly no
    ports: 
      - "127.0.0.1:9851:9851" 
    networks:
      - backend
    restart: always

networks:
  backend:
    name: backend
    external: true

volumes:
  postgres:
    name: postgres
  redis:
    name: redis