version: "3.8"

services:
  frontend:
    image: joseluisq/static-web-server:2
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=80
      - SERVER_ROOT=/public
    volumes:
      - ./dashboarddeelmobiliteit-app-main/build:/public
    networks:
      - backend
    ports:
      - "127.0.0.1:9000:80"
    restart: always

networks:
  backend:
    name: backend
    external: false